### ISSUE TITLE
Samsung TV not working

### ISSUE THREAD

**Issue by Digitiv-Inc** [mmende/homebridge-samsungtv-control#5] opened 2016-08-14 01:26 UTC
Hey thanks for the efforts! I was really hoping this would work for me, however my 75 inch samsung smart LED doesn't seem to be responding to it.. 

Would you happen to know if my tv model is supported : 
Model :UN75J6300AFXZC 
Version no : TH01  
URL : http://www.samsung.com/ca/consumer/tv-av/tv/led/UN75J6300AFXZC 

I followed your instructions, got the homebridge to be recognized/added : ( whenever I tap on it all i get is the disconnected message seen below from terminal) - 

![screenshot 2016-08-09 14 46 45](https://cloud.githubusercontent.com/assets/12852035/17646544/415e8914-619c-11e6-9a41-d46570c4e396.png)

so I can it's set up right because it's responding, however my TV is just refusing to listen to homebridge, The switch simply does nothing. from the home app itself. 

any advice would be highly appreciated. 

Thanks again!

**Comment by mmende** [comment] 2016-08-15 07:27
Hi,
The technique being used in this plugin unfortunately seems not to work with newer samsung models (especially when they are running Tizen as OS). I will see what I can do about that by using official samsung apis in the next weeks and hope to find a solution to work on both the legacy smart tv OS (a.k.a. Orsay) and smart tv's running Tizen.

PS: ...if anybody is more involved in samsungs smart tv api jungle I would appreciate every advice a can get.

**Comment by Astroman** [comment] 2016-08-17 16:33
I don't know if this helps, but the iOS app myTifi is able control my UN65KS8000, including turning it on. Therefore, it is indeed possible. :)

**Comment by rqui** [comment] 2016-10-03 09:28
same problem here..

**Comment by mmende** [comment] 2016-10-03 13:47
Yeah I know this app, but there is no official (or unofficial) implementation or documentation for the new remote control api right now as far as I know.
Duplicate of issue #1

**Closed as completed by mmende** 2016-10-03 13:47 UTC
